sudo: false
matrix:
  fast_finish: true
  include:
    - python: "3.5"
      env: TOXENV=lint
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
cache:
  directories:
    - $HOME/.cache/pip
install: pip install -U tox coveralls
language: python
script: tox
after_success: coveralls
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    tags: true
    repo: opsdroid/opsdroid
    condition: "$TOXENV = py35"
