os: linux
dist: xenial
jobs:
  fast_finish: true
  include:
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.7"
      env: TOXENV=docker
    - python: "3.7"
      env: TOXENV=docs
    - python: "3.7"
      env: TOXENV=lint
cache:
  directories:
    - $HOME/.cache/pip
services:
  - docker
install: pip install -U tox codecov
language: python
script: tox
after_success: codecov
deploy:
  provider: pypi
  username: $PYPI_USER
  password: $PYPI_PASSWORD
  cleanup: false
  on:
    tags: true
    repo: opsdroid/opsdroid
    condition: "$TOXENV = py37"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e03aa35a69fab2cb086a
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
