site_name: opsdroid
repo_url: https://github.com/opsdroid/opsdroid
theme: readthedocs

pages:
      - "Home": "index.md"
      - "Configuration Reference": "configuration-reference.md"
      - "REST API": "rest-api.md"
      - "Tutorial":
              - "Introduction": "tutorials/introduction.md"
              - "Create a Basic Skill": "tutorials/basic-skill.md"
              - "Introduction to Vim": "tutorials/introduction-vim.md"
      - "Example Skills":
              - "Introduction": "examples/introduction.md"
              - "Weather": "examples/weather.md"
      - "Extending opsdroid":
              - "Introduction": "extending/intro.md"
              - "Adding skills": "extending/skills.md"
              - "Adding connectors": "extending/connectors.md"
              - "Adding databases": "extending/databases.md"
              - "Using Events": "extending/events.md"
              - "Extension packaging": "extending/packaging.md"
      - "Connectors":
              - "Facebook": "connectors/facebook.md"
              - "GitHub": "connectors/github.md"
              - "Gitter": "connectors/gitter.md"
              - "Matrix": "connectors/matrix.md"
              - "Mattermost": "connectors/mattermost.md"
              - "Rocket.Chat": "connectors/rocketchat.md"
              - "Shell": "connectors/shell.md"
              - "Slack": "connectors/slack.md"
              - "Telegram": "connectors/telegram.md"
              - "Webex Teams": "connectors/webexteams.md"
              - "Websocket": "connectors/websocket.md"
      - "Databases":
              - "MongoDB": "databases/mongo.md"
              - "Redis": "databases/redis.md"
              - "SQLite": "databases/sqlite.md"
      - "Matchers":
              - "Simple":
                      - "Parse Format": "matchers/parse_format.md"
                      - "Regular Expressions": "matchers/regex.md"
              - "Third party NLU":
                      - "Dialogflow (Api.ai)": "matchers/dialogflow.md"
                      - "LUIS.AI": "matchers/luis.ai.md"
                      - "IBM Watson": "matchers/watson.md"
                      - "Rasa NLU (local)": "matchers/rasanlu.md"
                      - "Recast.AI (SAPCAI)": "matchers/sapcai.md"
                      - "wit.ai": "matchers/wit.ai.md"
              - "Misc":
                      - "Always": "matchers/always.md"
                      - "Crontab": "matchers/crontab.md"
                      - "Event": "matchers/event.md"
                      - "Webhook": "matchers/webhook.md"
      - "Constraints": "constraints.md"
      - "Contributing": "contributing.md"
      - "Project":
              - "Supported Python Versions": "project/supported-python-versions.md"
              - "Releasing": "project/making-a-release.md"
              - "Maintainers Guide": "maintainers.md"
