site_name: opsdroid
repo_url: https://github.com/opsdroid/opsdroid
theme: readthedocs

pages:
  - Home: 'index.md'
  - Getting Started: 'getting-started.md'
  - Configuration Reference: 'configuration-reference.md'
  - REST API: 'rest-api.md'
  - Extending opsdroid:
    - Adding skills: 'extending/skills.md'
    - Adding connectors: 'extending/connectors.md'
    - Adding databases: 'extending/databases.md'
  - Parsers:
    - Overview: 'parsers/overview.md'
    - Regular Expressions: 'parsers/regex.md'
    - API.AI: 'parsers/api.ai.md'
    - Crontab: 'parsers/crontab.md'
    - Webhook: 'parsers/webhook.md'
  - Contributing: 'contributing.md'
