site_name: opsdroid
repo_url: https://github.com/opsdroid/opsdroid
theme: readthedocs

pages:
  - 'Home': 'index.md'
  - 'Configuration Reference': 'configuration-reference.md'
  - 'REST API': 'rest-api.md'
  - 'Tutorial':
      - 'Introduction': 'tutorials/introduction.md'
      - 'Create a Basic Skill': 'tutorials/basic-skill.md'
      - 'Create a Weather Skill': 'tutorials/create-weather-skill.md'
  - 'Extending opsdroid':
      - 'Adding skills': 'extending/skills.md'
      - 'Adding connectors': 'extending/connectors.md'
      - 'Adding databases': 'extending/databases.md'
  - 'Matchers':
      - 'Regular Expressions': 'matchers/regex.md'
      - 'Rasa NLU (local)': 'matchers/rasanlu.md'
      - 'Dialogflow (Api.ai)': 'matchers/dialogflow.md'
      - 'LUIS.AI': 'matchers/luis.ai.md'
      - 'Recast.AI': 'matchers/recast.ai.md'
      - 'wit.ai': 'matchers/wit.ai.md'
      - 'Crontab': 'matchers/crontab.md'
      - 'Webhook': 'matchers/webhook.md'
      - 'Always': 'matchers/always.md'
  - 'Contributing': 'contributing.md'
  - 'Releasing': 'project/making-a-release.md'
  - 'Maintainers': 'maintainers.md'
