site_name: opsdroid
repo_url: https://github.com/opsdroid/opsdroid
theme: readthedocs

pages:
  - Home: 'index.md'
  - Configuration Reference: 'configuration-reference.md'
  - REST API: 'rest-api.md'
  - Extending opsdroid:
    - Adding skills: 'extending/skills.md'
    - Adding connectors: 'extending/connectors.md'
    - Adding databases: 'extending/databases.md'
  - Matchers:
    - Overview: 'matchers/overview.md'
    - Regular Expressions: 'matchers/regex.md'
    - Dialogflow (Api.ai): 'matchers/dialogflow.md'
    - LUIS.AI: 'matchers/luis.ai.md'
    - wit.ai: 'matchers/wit.ai.md'
    - Crontab: 'matchers/crontab.md'
    - Webhook: 'matchers/webhook.md'
    - Always: 'matchers/always.md'
  - Contributing: 'contributing.md'
