welcome-message: bool()


connectors:
  list(include('websocket', required=False),
  include('shell', required=False),
  include('ciscospark',required=False),
  include('facebook',required=False),
  include('github',required=False),
  include('matrix',required=False),
  include('slack',required=False),
  include('telegram',required=False),
  include('twitter',required=False))



databases:
  list(include('mongo', required=False),
  include('redis', required=False),
  include('sqlite', required=False),required=False)


skills: list(include('skill',required=False))


parsers: list(include('parser',required=False),required=False)

---
mongo:
  name: regex('^mongo$')
  host: str(required=False)
  port: regex('(^\d+$)',required=False)
  database: str(required=False)

---
redis:
  name: regex('^redis$')
  host: str(required=False)
  port: regex('(^\d+$)',required=False)
  database: regex('(^\d+$)',required=False)
  password: str(required=False)
  reconnect: bool(required=False)
---
sqlite:
    name: regex('^sqlite$')
    file: regex('(^\\\\?([^\\/]*[\\/])*)([^\\/]+)$',required=False)
    table: str(required=False)
---
websocket:
  name: regex('^websocket$')
  bot-name: str(required=False)
  max-connections: int(required=False)
  connection-timeout: int(required=False)
---
shell:
  name: regex('^shell$')
  bot-name: str(required=False)

---
ciscospark:
    name: regex('^ciscospark$')
    webhook-url:  str()
    access-token: str()
---
facebook:
    name: regex('^facebook$')
    verify-token: str()
    page-access-token: str()
    bot-name: str(required=False)
---
github:
    name: regex('^github$')
    github-token: str(required=False)
---
matrix:
    name: regex('^matrix$')
    mxid: regex('^\@[a-zA-Z]*:matrix.org$')
    password: str()
    room: str()
    rooms: (include('room1'))
    homeserver: regex('^https://matrix.org$')
    nick: str(required=False)
    room_specific_nicks: bool(required=False)
    send_m_notice: bool(required=False)

---
room1:
  'main': regex('^#matrix:matrix.org')
  'other': regex('^#riot:matrix.org$')

---
 slack:
   name: regex('^slack$')
   api-token: str()
   bot-name: str(required=False)
   default-room: str(required=False)
   icon-emoji: str(required=False)
   connect-timeout: int(required=False)

---
telegram:
    name: regex('^telegram$')
    token: str()
    update_interval: num(required=False)
    default_user: str(required=False)
    whitelisted_users: list(str(),str())

---
twitter :
    name: regex('^twitter$')
    consumer_key: str()
    consumer_secret: str()
    oauth_token: str()
    oauth_token_secret: str()
    enable_dms: bool(required=False)
    enable_tweets: bool(required=False)

---
skill:
    name : str()
---
parser:
    name: str()
    access-token: str(required=False)
    min-score: num(required=False)
    project: str(required=False)
    token: str(required=False)
    enabled: bool(required=False)
    appid: str(required=False)
    appkey: str(required=False)
    verbose: bool(required=False)
