name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  check:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        component: [docker-full, docker-min, lint]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -U tox
      - name: Run checks
        run: tox -vv -e ${{ matrix.component }}
        timeout-minutes: 30
